### ISSUE TITLE
using include_vars variables defined there not being used

### ISSUE THREAD

**Issue by shadjifotis** [WillsherSystems/ansible-users#5]
``` yaml

---
# file: cmservers.yml
- hosts: cmservers
  tasks:
     - include_vars: /var/cm/local/ansible/vars/cmusers.yml
  roles:
   - ansible-users-master
```

``` yaml

---
# file: vars/cmservers.yml

users_default_shell: /bin/bash
users_per_user_groups: false
users_manage_admin_sudoers: false

users:
- name: shadjifo2
#  state: absent
  state: present
  uid: 20001
  comment: 'Sebastien Hadjifotis'
  is_admin: false
  group: primgroup
  groups:
  - extragroup

users_groups:
- name: primgroup
  gid: 29999
- name: extragroup
  gid: 39999
```

running cmservers,yml does not user the users hash defined in cmusers.yml
