### ISSUE TITLE
Allow omitted password

### ISSUE THREAD

**Issue by storeman** [WillsherSystems/ansible-users#6]
It may be out of the scope from this ansible role, but should it be possible to omit the password? I want to create local roles who shouldn't be able to login, thus without a password.

``` yml
#replace:
password: '{{ item.password | default(users_default_password) }}'
#with: 
password: '{{ item.password | default(omit) }}'
```

This breaks BC, so maybe it's not that a good idea. Or do you have a suggestion to get this done in with the current configuration?
