### ISSUE TITLE
Group not being deleted

### ISSUE THREAD

**Issue by shadjifotis** [WillsherSystems/ansible-users#7]
```

---
# file: cmservers.yml
- hosts: cmservers
  pre_tasks:
     - include_vars: /var/cm/local/ansible/vault/cmservers
     - include_vars: /var/cm/local/ansible/vars/appusers.yml
     - include_vars: /var/cm/local/ansible/vars/cmusers.yml
     - local_action: "command openssl passwd -salt '{{ cm_default_password_salt }}' -1 '{{ cm_default_password }}'"
       run_once: True
       register: password_hash
       changed_when: False
     - set_fact: users_default_password="{{ password_hash.stdout }}"
#     - debug: var=password_hash
#     - debug: var=users_default_password
#     - debug: msg="Default hash is {{ users_default_password }}"
#     - debug: var=users
  roles:
   - {role: ansible-users-master, users: "{{ cmusers }}", groups: "{{ cmusers_groups }}"}
   - {role: ansible-users-master, users: "{{ appusers }}", groups: "{{ appusers_groups }}"}
```

From /var/cm/local/ansible/vars/appusers.yml

```
appusers_groups:
- name: jazzadmin
  state: absent
  gid: 578

Should the group be removed during the remove group task?

TASK: [ansible-users-master | Remove group] ***********************************
skipping: [miluvl162]

TASK: [ansible-users-master | Remove per-user groups] *************************
```
